# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: check

  check:
    cmds:
      - dprint check
      - biome check

  fmt:
    cmds:
      - dprint fmt
      - treefmt

  serve:
    cmds:
      - echo 'Listening on http://localhost:8000'
      - caddy file-server --listen :8000 --root public
