# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: check

  check:
    cmds:
      - dprint check
      - biome check

  fmt:
    cmds:
      - dprint fmt
      - treefmt

  serve:
    deps:
      - task: get-dependencies
    cmds:
      - caddy file-server --listen :8000 --root public

  get-dependencies:
    cmds:
      - mkdir -p public/vendor
      - nix build .#nanoreset --out-link public/vendor/nanoreset.min.css
