name: Lint
on:
  push:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'LICENSE'
jobs:
  asdf-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: kachick/action-parse-asdf-tool-versions@2687202f12ef718e0c6584402a02b18ba8fa92be
        id: parse
    outputs:
      tool-versions: '${{ steps.parse.outputs.json }}'
  css:
    needs: [asdf-parser]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: antongolub/action-setup-bun@v1
        with:
          bun-version: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).bun }}'
      - run: bun install
      - run: bun run lint

  dprint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.1
