name: Lint
on:
  push:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'LICENSE'
jobs:
  css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.29.3
      - run: deno run --node-modules-dir --allow-env --allow-read npm:stylelint '**/*.css'

  dprint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.1
